---
# - name: Gather facts
#   tags: always
#   import_playbook: ../kubespray/facts.yml

- name: Kubespray extranet preinstall
  hosts: k8s_cluster:etcd
  gather_facts: True
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env }}"  
  roles:
    - role: kubespray-defaults
    - role: dummy-extranet
      tags: "dummy-extranet"
      when: dummy_extranet_enabled
    - role: "container-engine/docker"
      tags: "kubespray-file-server"
      when:
        - deploy_container_engine
        - deploy_kubespray_file_server
    - role: kubespray-file-server
      tags: "kubespray-file-server"
      when: deploy_kubespray_file_server
