all:
  hosts:
    node1:
      ansible_host: INTERNAL_IP_1
      ip: PUBLIC_IP_1
      access_ip: PUBLIC_IP_1
      etcd_address: INTERNAL_IP_1
      deploy_container_engine: false
    node2:
      ansible_host: PUBLIC_IP_2
      ip: PUBLIC_IP_2
      access_ip: PUBLIC_IP_2
    node3:
      ansible_host: PUBLIC_IP_3
      ip: PUBLIC_IP_3
      access_ip: PUBLIC_IP_3
    node4:
      ansible_host: PUBLIC_IP_4
      ip: PUBLIC_IP_4
      access_ip: PUBLIC_IP_4
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node[1:4]:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        k8s_cluster_cloud:
    k8s_cluster_cloud:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    all_cloud:
      children:
        cloud_aliyun:
        cloud_huawei_north1:
        cloud_huawei_north4:
        cloud_tencent:
    cloud_aliyun:
      hosts:
        node1:
    cloud_huawei_north1:
      hosts:
        node2:
    cloud_huawei_north4:
      hosts:
        node3:
    cloud_tencent:
      hosts:
        node4:
