---
- name: Kubespray extranet preinstall
  import_playbook: extranet-preinstall.yml

- name: Check ansible version
  import_playbook: ../kubespray/ansible_version.yml

- name: Ensure compatibility with old groups
  import_playbook: ../kubespray/legacy_groups.yml

- hosts: bastion[0]
  gather_facts: False
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults}
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"]}

- hosts: etcd[0]
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults}
    - { role: recover_control_plane/etcd, when: "not etcd_kubeadm_enabled|default(false)" }

- hosts: kube_control_plane[0]
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults}
    - { role: recover_control_plane/control-plane }

- name: Deploy cluster
  import_playbook: ../kubespray/cluster.yml

- hosts: kube_control_plane
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults}
    - { role: recover_control_plane/post-recover }
